### ISSUE TITLE
Automated tests: fix flaky FreeTrialSpec

### ISSUE THREAD

**Issue by jbuabbud** [DataBiosphere/firecloud-app#92] opened 2018-06-19 18:49 UTC
FreeTrialSpec - "A user whose free trial status is enabled should be able to see the free trial banner, enroll and get terminated" is failing and needs to be fixed. I've been tasked with running it once manually for confirmation that it can be ignored for the release tomorrow 6/20. I will also attempt to fix the failing test.

**Comment by davidangb** [comment] 2018-06-19 21:42
very initial observations:
* this test - `"should be able to see the free trial banner, enroll and get terminated"` - is the one `FreeTrialSpec` test that creates a project. We are timing out inside of `FreeTrialSpec.setUpEnabledUserAndProject`, which is the method that creates the project.
* ultimately, free trial project creation calls workbench-libs' `Orchestration.createTrialProjects`. This method:
    * calls `countTrialProjects`, which we expect to return 0;
    * issues a call to create a project;
    * sits in a `Retry.retry` loop calling `countTrialProjects` every 30 seconds until the project count reaches our target (of 1).
* the test stack trace looks like it is timing out in `countTrialProjects`. If you scroll back in the test log, you'll see that `countTrialProjects` has succeeded a few times already.
* the underlying root cause - I bet $2 - is that project creation is too slow (see #30), and causing delays. But I don't know why this is happening more frequently, or why our retry code isn't successfully handling errors correctly.

**Comment by irosenbe** [comment] 2018-07-17 18:34
Resolved in #30

**Closed by irosenbe** 2018-07-17 18:34 UTC
