### ISSUE TITLE
Bug with uploading membership files

### ISSUE THREAD

**Issue by tmm211** [DataBiosphere/firecloud-app#202] opened 2018-10-02 21:19 UTC
Reported on the forum:
https://gatkforums.broadinstitute.org/gatk/discussion/comment/52616#Comment_52616

I was able to replicate it by downloading a sample_set, which provided a folder with both a sample_set_entity.tsv and sample_set_membership.tsv.

Then I reuploaded the membership file and it worked. I don't believe it should work. I know have duplicates:
<img width="1325" alt="screen shot 2018-10-02 at 4 53 27 pm" src="https://user-images.githubusercontent.com/13475639/46376360-d0168980-c663-11e8-94a8-5763b28c280c.png">

**Comment by davidangb** [comment] 2018-10-03 13:17
@irosenbe yes, this would be present in Saturn as well. If we want to fix it for Saturn, we should make sure to make code changes in Rawls, not Orchestration.

This bug has been around forever - see [GAWB-694](https://broadinstitute.atlassian.net/browse/GAWB-694) or https://gatkforums.broadinstitute.org/firecloud/discussion/10095/duplicate-entities-in-entity-sets.

**Comment by irosenbe** [comment] 2018-10-09 12:16
Moving to backlog for now due to higher priority OKRs for this quarter.

**Comment by davidangb** [comment] 2018-10-09 18:05
probably a dupe of #183

**Comment by rebrown1395** [comment] 2018-12-06 21:51
Won't fix.

**Closed by rebrown1395** 2018-12-06 21:51 UTC
Labels: bug
