### ISSUE TITLE
Better feedback when downloading a >2GB file from FireCloud via UI

### ISSUE THREAD

**Issue by knoblett** [DataBiosphere/firecloud-app#186] opened 2018-09-18 15:48 UTC
Reported by a user [here](https://gatkforums.broadinstitute.org/firecloud/discussion/12949/download-file-from-link-in-data-model-is-failing).

We provide a gsutil command for folks to use when trying to download files >2GB. However, if the user clicks on the link to save via the UI, they are given a json-like output rather than the file they were looking to download.

I'd like to either disable the link (if we don't want folks to try downloading the file if it is >2GB in size) or give the user better feedback when they try to click the link. Something like, "You cannot download files larger than 2 GB using this link. Please try the gsutil command listed below."

**Comment by davidangb** [comment] 2018-09-25 19:44
curious: I see this bug in production, but don't see it in dev - even when referencing the same file to download.

**Comment by davidangb** [comment] 2018-09-25 19:51
closing as duplicate of GAWB-3642.

**Closed by davidangb** 2018-09-25 19:51 UTC
