### ISSUE TITLE
"Illegal character in scheme name at index" Whitespaces

### ISSUE THREAD

**Issue by bshifaw** [DataBiosphere/firecloud-app#166] opened 2018-08-29 19:35 UTC
When users copy path to a file (possibly from FC UI) whitespaces or trailing characters are copied along that cause the following error to pop up when used as input in the method configuration. 
`Illegal character in scheme name at index`

https://gatkforums.broadinstitute.org/firecloud/discussion/comment/50524#Comment_50524
https://gatkforums.broadinstitute.org/firecloud/discussion/12611/charges-for-failed-runs#latest
https://gatkforums.broadinstitute.org/firecloud/discussion/comment/50745#Comment_50745

**Comment by davidangb** [comment] 2018-09-25 18:05
duplicate of #110; closing.

**Closed by davidangb** 2018-09-25 18:05 UTC
